### ISSUE TITLE
Use new service-services-service endpoint

### ISSUE THREAD

**Issue by kvisscher** [springtreesolutions/eva-tester#7] opened 2018-10-03 13:40 UTC
Instead of GETting `/services` do a `POST` to  `/message/GetAvailableServices` and for the details `POST` to `/message/GetAvailableServiceDetails`

**Comment by realappie** [comment] 2018-11-07 15:28
NOT A BUG

**Comment by realappie** [comment] 2019-03-06 10:24
Closed by https://github.com/springtreesolutions/eva-tester/commit/a5caa7827a1061e6bb8920cc29e1666a2072b2df

**Closed** 2019-03-06 10:30 UTC
Labels: enhancement
